FROM alpine

MAINTAINER Willem Essenstam <wessenstam.at@gmail.com>

# Get the to be needed stuff in
RUN apk add --no-cache python3 python3-dev libstdc++ g++ git py3-pip && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h  && \
# Install the python dependencies
    pip3 install --upgrade pip && \
    pip3 install flask &&\
    pip3 install influxdb-client


WORKDIR /

ADD probe_server.py .
ADD probe_server.sh .

EXPOSE 5000

CMD ["sh", "probe_server.sh"]
