version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/docker_data/grafana_data:/var/lib/grafana
    restart: always

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${PWD}/docker_data/influxdb:/root/.influxdbv2/
    restart: always
